// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhlakaBulkyWebApp.Data;

#nullable disable

namespace NhlakaBulkyWebApp.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20240321200633_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhlakaBulkyWebApp.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayOrder = 1,
                            Name = "Romance"
                        },
                        new
                        {
                            ID = 2,
                            DisplayOrder = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 3,
                            DisplayOrder = 3,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 4,
                            DisplayOrder = 4,
                            Name = "Kasi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
